SealManagement/Models/SignMaker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SealManagement.Models
{
    public class SignMaker
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 登录名
        /// </summary>
        [Required]
        [StringLength(50)]
        [DisplayName("用户名")]
        public string UserName { get; set; }
        /// <summary>
        /// 序列号
        /// </summary>
        [Required]
        [StringLength(50)]
        [DisplayName("序列号")]
        public string ArrayNo { get; set; }
        /// <summary>
        /// 证书base64
        /// </summary>
        [Required]
        [DisplayName("证书")]
        public string Certificator { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        [Required]
        [StringLength(30)]
        [DisplayName("创建日期")]
        public string CreateDate { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [DisplayName("备注")]
        public string Remark { get; set; }
        /// <summary>
        /// 删除标识
        /// </summary>
        [DisplayName("删除标识")]
        public int IsDelete { get; set; }
    }
}

SealManagement/Models/SignMakerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SealManagement.Models
{
    public class SignMakerViewModel
    {
        public SignMaker SignMaker { get; set; }
        public string ValidateCode { get; set; }
    }
}

SealManagement/Controllers/SignMakerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using NLog;
using Org.BouncyCastle.X509;
using SealManagement.Common;
using SealManagement.Extensions;
using SealManagement.Models;
using SealManagement.SqlData;

namespace SealManagement.Controllers
{
    [Authorize(Roles = "User")]
    public class SignMakerController : Controller
    {
        private readonly IMemoryCache _memoryCache;
        private SignContext _context;
        private static Logger logger = LogManager.GetCurrentClassLogger();
        private int usertype = (int)userType.User;
        public SignMakerController(SignContext context, IMemoryCache memoryCache)
        {
            _context = context;
            _memoryCache = memoryCache;
        }
        /// <summary>
        /// 显示用户列表
        /// </summary>
        /// <returns>返回用户列表界面</returns>
        //public async Task<IActionResult> Index()
        //{
        //    X509CertificateParser certificateParser = new X509CertificateParser();

        //    var users = await _context.SignMakers.Where(p => p.IsDelete == 0).ToListAsync() ?? null;
        //    var data = users.Select(s =>
        //    {
        //        //微软自带X509Certificate不认同项目中UKey，需要转为Org.BouncyCastle.X509.X509Certificate类型
        //        Org.BouncyCastle.X509.X509Certificate cert =
        //            certificateParser.ReadCertificate(Convert.FromBase64String(s.Certificator));
        //        return new SignMakerInfo()
        //        {
        //            SignMaker = s,
        //            Issuer = cert.IssuerDN.ToString(),
        //            Subject = cert.SubjectDN.ToString(),
        //            NotBefore = cert.NotBefore.ToString("yyyy-MM-dd HH:mm:ss"),
        //            NotAfter = cert.NotAfter.ToString("yyyy-MM-dd HH:mm:ss"),
        //        };
        //    });
        //    return View(data);
        //}
        public async Task<IActionResult> Index()
        {
            var guid = Guid.NewGuid();
            ViewData["ValidateCode"] = guid.ToString();
            HttpContext.Response.Cookies.Append("ValidateCode",
                Convert.ToBase64String(ToolClass.Encrypt(Encoding.UTF8.GetBytes(guid.ToString()))));
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(int PageSize = 10, int PageIndex = 1)
        {
            X509CertificateParser certificateParser = new X509CertificateParser();

            var users = await _context.SignMakers.Where(p => p.IsDelete == 0).Skip(PageSize * (PageIndex - 1)).Take(PageSize).ToListAsync() ?? null;
            var data = users.Select(s =>
            {
                //微软自带X509Certificate不认同项目中UKey，需要转为Org.BouncyCastle.X509.X509Certificate类型
                Org.BouncyCastle.X509.X509Certificate cert =
                certificateParser.ReadCertificate(Convert.FromBase64String(s.Certificator));
                return new SignMakerInfo()
                {
                    SignMaker = s,
                    Issuer = cert.IssuerDN.ToString(),
                    Subject = cert.SubjectDN.ToString(),
                    NotBefore = cert.NotBefore.ToString("yyyy-MM-dd HH:mm:ss"),
                    NotAfter = cert.NotAfter.ToString("yyyy-MM-dd HH:mm:ss"),
                };
            });
            var total = await _context.SignMakers.Where(p => p.IsDelete == 0).CountAsync();
            logger.Info($"获取制章人信息：获取成功");
            return Json(new { state = resultType.Success, data = data, total = total });
        }

        /// <summary>
        /// 显示单个用户详细信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Detail(string EncryptData)
        {
            if (!Define.IsChecked)
            {
                logger.Info($"显示制章人详情：获取失败|系统未经自检，请先执行自检后操作");
                return Json(new { state = resultType.Error, message = "系统未经自检，请先执行自检后操作" });
            }
            var jsonBack = ToolClass.EncryptTransit(EncryptData);
            //if (string.IsNullOrEmpty(jsonBack))
            //{
            //    return Json(new { state = resultType.Error, message = "参数错误" });
            //}
            if (int.TryParse(jsonBack, out var errorCodeValue))
            {
                var errorCode = (ErrorCode)errorCodeValue;
                logger.Info($"显示制章人详情：获取失败|错误码：{errorCodeValue}，错误信息：{ToolClass.GetDescription(errorCode)}");
                return Json(new { state = resultType.Error, message = $"错误码：{errorCodeValue}，错误信息：{ToolClass.GetDescription(errorCode)}" });
            }
            var EditModel = JsonConvert.DeserializeObject<EditModel>(jsonBack);
            if (EditModel == null)
            {
                logger.Info($"显示制章人详情：获取失败|数据不存在");
                return Json(new { state = resultType.Error, message = "数据不存在" });
            }

            var user = await _context.SignMakers.Where(u => u.Id == EditModel.Id).FirstAsync();
            X509CertificateParser certificateParser = new X509CertificateParser();
            Org.BouncyCastle.X509.X509Certificate cert =
                    certificateParser.ReadCertificate(Convert.FromBase64String(user.Certificator));
            var data = new SignMakerInfo()
            {
                SignMaker = user,
                Issuer = cert.IssuerDN.ToString(),
                Subject = cert.SubjectDN.ToString(),
                NotBefore = cert.NotBefore.ToString("yyyy-MM-dd HH:mm:ss"),
                NotAfter = cert.NotAfter.ToString("yyyy-MM-dd HH:mm:ss"),
            };
            logger.Info($"显示制章人详情：获取成功|UserID:{user.ArrayNo}");
            //return View(data);
            _memoryCache.Set("UserModelForSignMakerDetail", data);
            return Json(new { state = resultType.Success, data = data });
        }

        public async Task<IActionResult> DetailForViewShow()
        {
            return View("Detail", _memoryCache.Get("UserModelForSignMakerDetail") as SignMakerInfo);
        }
        //public async Task<IActionResult> Details(int id)
        //{
        //    var user = await _context.SignMakers.Where(u => u.Id == id).FirstAsync();
        //    X509CertificateParser certificateParser = new X509CertificateParser();
        //    Org.BouncyCastle.X509.X509Certificate cert =
        //            certificateParser.ReadCertificate(Convert.FromBase64String(user.Certificator));
        //    var data = new SignMakerInfo()
        //    {
        //        SignMaker = user,
        //        Issuer = cert.IssuerDN.ToString(),
        //        Subject = cert.SubjectDN.ToString(),
        //        NotBefore = cert.NotBefore.ToString("yyyy-MM-dd HH:mm:ss"),
        //        NotAfter = cert.NotAfter.ToString("yyyy-MM-dd HH:mm:ss"),
        //    };
        //    return Json(new { state = resultType.Success, data = data});
        //}
        /// <summary>
        /// 创建一个新用户
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var guid = Guid.NewGuid();
            ViewData["ValidateCode"] = guid.ToString();
            HttpContext.Response.Cookies.Append("ValidateCode",
                Convert.ToBase64String(ToolClass.Encrypt(Encoding.UTF8.GetBytes(guid.ToString()))));
            return View();
        }

        /// <summary>
        /// 创建一个新用户
        /// </summary>
        /// <param name="UserModel"></param>
        /// <returns></returns>
        [HttpPost]
        //public async Task<IActionResult> Create([FromBody]SignMaker UserModel)
        public async Task<IActionResult> Create(string EncryptData)
        {
            if (!Define.IsChecked)
            {
                logger.Info($"新增制章人：获取失败|系统未经自检，请先执行自检后操作");
                return Json(new { state = resultType.Error, message = "系统未经自检，请先执行自检后操作" });
            }
            var jsonBack = ToolClass.EncryptTransit(EncryptData);
            //if (string.IsNullOrEmpty(jsonBack))
            //{
            //    return Json(new { state = resultType.Error, message = "参数错误" });
            //}
            if (int.TryParse(jsonBack, out var errorCodeValue))
            {
                var errorCode = (ErrorCode)errorCodeValue;
                logger.Info($"新增制章人：获取失败|错误码：{errorCodeValue}，错误信息：{ToolClass.GetDescription(errorCode)}");
                return Json(new { state = resultType.Error, message = $"错误码：{errorCodeValue}，错误信息：{ToolClass.GetDescription(errorCode)}" });
            }
            var signMakerViewModel = JsonConvert.DeserializeObject<SignMakerViewModel>(jsonBack);
            if (signMakerViewModel == null)
            {
                logger.Info($"新增制章人：获取失败|数据不存在");
                return Json(new { state = resultType.Error, message = "数据不存在" });
            }
            #region cookie验证
            var guidStr = "";
            if (!HttpContext.Request.Cookies.TryGetValue("ValidateCode", out guidStr))
            {
                logger.Info($"新增制章人：获取失败|cookie未设置，请联系管理员");
                return Json(new { state = resultType.Error, message = "cookie未设置，请联系管理员" });
            }
            var guidFromCookie = Encoding.UTF8.GetString(ToolClass.Decrypt(Convert.FromBase64String(guidStr)));
            if (!string.Equals(guidFromCookie, signMakerViewModel.ValidateCode, StringComparison.OrdinalIgnoreCase))
            {
                logger.Info($"新增制章人：获取失败|cookie不正确，请刷新页面后重试");
                return Json(new { state = resultType.Error, message = "cookie不正确，请刷新页面后重试" });
            }
            #endregion
            var signMaker = signMakerViewModel.SignMaker;
            var arrayno = signMaker.ArrayNo;

SealManagement/Views/SignMaker/Create.cshtml
@{
    ViewData["Titel"] = "添加制章人";
}

<h2 style="margin:20px 0">添加制章人</h2>


<script src="~/js/utils.js"></script>
<div class="form-horizontal">
    <h4>请插入制章人UKEY后点击按钮进行添加</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt></dt>
        <dd><h4 id="h4Title" class="text-danger" style="display: none">请稍等，正在进行UKEY验证……</h4></dd>
    </dl>
    <div class="form-group">
        <div id="waitingPicDiv" class="col-md-offset-2 col-md-10" style="display: none">
            <img src="~/Content/waiting_transparent.gif" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-6">
            
            <form class="form-horizontal">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-3 control-label">用户名</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="UserName" name="UserName">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-3 control-label">备注</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="Remark" name="Remark">（无特殊说明可空）
                    </div>
                </div>
                @*新修改部分*@
                <div class="form-group">

                    <div class="col-sm-offset-2 col-sm-10" style="display:none">
                        <input type="text" class="form-control" id="ArrayNo" name="ArrayNo" placeholder="certSN">
                    </div>
                    <div class="col-sm-offset-2 col-sm-10" style="display:none">
                        <input type="text" class="form-control" id="Certificator" name="Certificator" placeholder="certBase64">
                    </div>

                    <label for="ukeySelect" class="col-sm-3 control-label">请选择UKEY</label>
                    <div class="col-sm-9" style="line-height: 30px;">
                        <select id="ukeySelect" name="ukeySelect" lay-filter="ukeySelect" class="form-control" ></select>
                    </div>
                    <div class="col-sm-offset-6 col-sm-10" style="margin-top:20px;">
                        <a><input type="button" class="btn btn-default" value="添加制章人" id="btnCreate" /></a>
                    </div>
                </div>
            </form>

        </div>
           
        </div>
    </div>
    <dl id="infoDiv" class="dl-horizontal" style="display: none">
        <dt>@*当前进度：*@</dt>
        <dd></dd>
    </dl>
    <div id="debug" style="display: none"></div>


@section scripts {
    <script src="/Content/layui/layui.js" charset="utf-8"></script>
    <script src="~/js/dateformat.js"></script>
    <script>
       
        function initlist(str) {
            
            if (str == "") {
            	$("select[name='ukeySelect']").empty();
            }
            //转换成js对象并赋值
            let obj = $.parseJSON(str);
            //使失去焦点
            $("select[name='ukeySelect']").blur();
            //清空子元素
            $("select[name='ukeySelect']").empty();
            //遍历对象生成节点
            $(obj.CertInfolist).each(function(index, value) {
            	$("select[name='ukeySelect']").append("<option value='" + value.CertID + "'>" + value.CertCN + "</option>")
            })

        }
        function myPost(url, args) {
            var body = $(document.body),
                form = $("<form method='post' id='myform'></form>"),
                input;
            form.attr({ "action": url });
            $.each(args, function (key, value) {
                input = $("<input type='hidden'>");
                input.attr({ "name": key });
                input.val(value);
                form.append(input);
            });

            form.appendTo(document.body);
           
            var params = $("#myform").serialize();
            console.log(params);
            $.post(url, params, function (e) {
                console.log(e);
                if (e.state == 200) {
                    layer.msg("成功添加制章人");
                    window.location.href = '/SignMaker/Index';
                } else {
					 $('#UserName').val('')
                    layer.msg(e.message);
                }
            })
            
            if (FormData != null) {
                //FormData.
            }
            document.body.removeChild(form[0]);
        }
       
        //新修改部分
        $(function () {
            EnumKey(function (data) {
                initlist(data);
                console.log("--------");     
                console.log(data);
            },
                function () {
                    layui.use('layer',
                        function () {
                            var layer = layui.layer;
                            layer.msg("未安装UKEY支持服务！");
                        });
                });
            //console.log("111111--------");
            //新修改部分
            $('#btnCreate').click(function () {
				var base64 = new Base64();
                console.log($("#ukeySelect").val());
                var certSN = $("#ukeySelect").val();
                GetCertAndSeal(certSN, function (certAndSeal) {
                    var certAndSealJObject = JSON.parse(certAndSeal);
                    console.log(certAndSeal);
                    if (certAndSealJObject.CertBase64.length != 0) {
                        var certBase64 = certAndSealJObject.CertBase64;
                        DisplayMessage("正在获取UKEY序列号");
                        $('#ArrayNo').val(certSN);
                        $('#Certificator').val(certBase64);

                        var UserName = $('#UserName').val();
                        var ArrayNo = $('#ArrayNo').val();
                        var Certificator = $('#Certificator').val();
                        var Remark = $('#Remark').val();
                        var ukeySelect = $('#ukeySelect').val();

                        if (UserName == '' || UserName == 'undefined') {
                            layer.msg('用户名不能为空');
                            return;
                        }
                       EncryptCertList((data) => {
                       	data = JSON.parse(data);
let CertID = getCookie("CertID");
                       	//加密的字符串
                       	var str = JSON.stringify({
							SignMaker:{
								
								UserName: UserName, //用户名
								ArrayNo: ArrayNo, //不知道
								Certificator: Certificator, //不知道
								Remark: Remark, //备注
								ukeySelect: ukeySelect ,//选的ukey
							},
							
							validatecode:"@ViewBag.ValidateCode"
                       	});
                       
                       	var External = {
                       		CertID: CertID,
                       		//编码
                       		DataBase64: base64.encode(str)
                       	};
                       
                       	ExternalEncrypt(JSON.stringify(External), (data) => {
                       		data = JSON.parse(data);
                                  if (data.error == "Ok") {
                                      var dataToPost = {
                                          // ArrayNo: CertID,
                                          EncryptData: data.contentBase64
                                      };
                                      DisplayMessage("正在向服务器发送验证数据");
                                      myPost("/SignMaker/Create", dataToPost, function (data) {
                                          console.log(data);
                                      });
                                  }  else {
                                layer.msg(data.error)
                            }
                       	});
                       })
                    }
                });



            });
        });
    </script>
}

SealManagement/Views/SignMaker/Detail.cshtml
@model SealManagement.Models.SignMakerInfo

@{
    ViewData["Title"] = "制章人详情";
}
<h2 style="margin:20px 0">制章人详情</h2>
<hr />

		<script src="~/js/utils.js"></script>
		<script src="~/lib/jquery/jquery-1.12.4.js"></script>
<div class="table-responsive">
    <table class="table table-bordered  table-condensed">
        <thead>
            <tr class="row mx-0" >
                <th class="text-center col-md-1">@Html.DisplayNameFor(model => model.SignMaker.UserName)</th>
                <th class="col-md-2 text-center ">@Html.DisplayNameFor(model => model.SignMaker.ArrayNo)</th>
                <th class="text-center col-md-2">@Html.DisplayNameFor(model => model.Subject)</th>
                <th class="text-center col-md-2">@Html.DisplayNameFor(model => model.Issuer)</th>
                <th class="text-center  col-md-1">@Html.DisplayNameFor(model => model.SignMaker.Certificator)</th>
                <th class="text-center  col-md-1">@Html.DisplayNameFor(model => model.SignMaker.CreateDate)</th>
                <th class="text-center  col-md-1">@Html.DisplayNameFor(model => model.SignMaker.Remark)</th>
                <th class="text-center col-md-1">@Html.DisplayNameFor(model => model.NotBefore)</th>
                <th class="text-center col-md-1">@Html.DisplayNameFor(model => model.NotAfter)</th>
            </tr>
        </thead>
        <tbody>
            <tr class="text-center row  mx-0">
                <td class="col-md-1">
                    @Html.DisplayFor(model => model.SignMaker.UserName)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(model => model.SignMaker.ArrayNo)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(model => model.Subject)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(model => model.Issuer)
                </td>
                <td class="col-md-1">
                    <a id="a" style="cursor: pointer;">点击下载</a>
                    <!-- @Html.ActionLink("点击下载", "DownCert", "SignMaker", new { id = Model.SignMaker.Id }); -->
                </td>
                <td class="col-md-1">
                    @Html.DisplayFor(model => model.SignMaker.CreateDate)
                </td>
                <td class="col-md-1">
                    @Html.DisplayFor(model => model.SignMaker.Remark)
                </td>
                <td class="col-md-1">
                    @Html.DisplayFor(model => model.NotBefore)
                </td>
                <td class="col-md-1">
                    @Html.DisplayFor(model => model.NotAfter)
                </td>
            </tr>
        </tbody>
    </table>
</div>
<script type="text/javascript">
	$(function(){
		$("#a").click(()=>{
			down(@Model.SignMaker.Id);
		})
	})
	function down(id) {
		let base64 = new Base64();
		EncryptCertList((data) => {
			data = JSON.parse(data);
			
let CertID = getCookie("CertID");
			//加密的字符串
			var str = JSON.stringify({
				Id: id
			});
			var External = {
				CertID: CertID,
				//编码
				DataBase64: base64.encode(str)
			};
	
			ExternalEncrypt(JSON.stringify(External), (data) => {
				data = JSON.parse(data);
				if (data.error == "Ok") {
					var d = data.contentBase64;
					var reg = new RegExp('\\+', "g")
					var dd = d.replace(reg, '%2B');
					location.href = "/SignMaker/DownCert?EncryptData=" + dd;
					
				} else {
                                layer.msg(data.error)
                            }
			});
		})
	}
</script>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>*@ 
    <a asp-action="Index">跳回列表页面</a>
</div>

SealManagement/Views/SignMaker/Edit.cshtml
@model SealManagement.Models.SignMaker

@{
    ViewData["Title"] = "编辑制章人";
}

<!DOCTYPE html>

<html>
<head>
	
	<script src="~/js/utils.js"></script>
    <script src="~/lib/jquery/jquery-1.12.4.js"></script>
    <script src="~/lib/jquery/jquery-1.12.4.min.js"></script>
    <script>
        $(function () {
            $('#btnSave').click(function () {
				var base64 = new Base64();
                var UserName = $('#UserName').val();
                var Remark = $('#Remark').val();
                var Id = $('#Id').val();
                EncryptCertList((data) => {
                	data = JSON.parse(data);
let CertID = getCookie("CertID");
                	//加密的字符串
                	var str = JSON.stringify({
						SignMaker:{
							
							UserName: UserName, //用户名
							Remark: Remark, //备注
							Id: Id,
						},
						
						validatecode:"@ViewBag.ValidateCode"
                	});
                
                	var External = {
                		CertID: CertID,
                		//编码
                		DataBase64: base64.encode(str)
                	};
                
                	ExternalEncrypt(JSON.stringify(External), (data) => {
                		data = JSON.parse(data);
                        if (data.error == "Ok") {
                            var dataToPost = {
                                // ArrayNo: CertID,
                                EncryptData: data.contentBase64
                            };
                            $.ajax({
                                url: "/SignMaker/EditForSignMaker",
                                type: 'POST',
                                // contentType: 'application/json',
                                // dataType: 'JSON',
                                data: dataToPost,
                                success: function (data) {
                                    if (data != null && data.state == '200') {
                                        layer.msg('保存成功', { time: 500 }, function () {
                                            window.location.href = '/SignMaker/Index';
                                        });

                                    } else {
                                        layer.msg(data.message);
                                        $('#UserName').val('')
                                        return;
                                    }
                                }
                            });
                        }  else {
                                layer.msg(data.error)
                            }
                	});
                })
                
            });
        })
    </script>

</head>
<body>

    <h2 style="margin:20px 0">编辑制章人</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" id="Id" />
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" id="UserName" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                @*修改变量名*@
                <div class="form-group">
                    <label asp-for="Remark" class="control-label"></label>
                    <input asp-for="Remark" class="form-control" id="Remark" />
                    <span asp-validation-for="Remark" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="button" value="保存" id="btnSave" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">返回列表页面</a>
    </div>

</body>
</html>